install:
  - ps: Install-Product node 8
  - node --version
  - npm install npm@latest -g
  - npm --version
  - npm install
build_script:
 - npm run dist
 - cd dist
 - msiexec /i "KioskDemoElectron.msi" /l*v "install.log" KIOSK_USERNAME=%username% SERVER_URL=https://ciserver TOKEN=citoken
artifacts:
  - path: .\dist\*.msi
  - path: .\dist\*.log
  - path: C:\Windows\SysWOW64\powershell.log