install:
  - ps: Install-Product node 8
  - node --version
  - npm --version
  - npm install
build_script:
 - npm run dist
artifacts:
  - path: .\dist\*.msi
    name: installer
  - path: C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\*-debug.log
    name: npm-logs